### ISSUE TITLE
CA's obligation for TOS Security Consideration

### ISSUE THREAD

**Issue by ounsworth** [vanbroup/acme-auto-discovery#12]
We could add to 8.4.1 something to the effect of:

> CAs will typically provide documentation indicating how to configure a domain's CAA record for ACME auto-discovery. CAs are encouraged to note in alongside those instructions that doing so will be taken as implicit agreement to the Terms of Service, and also to include a direct link to those Terms of Service.

**Comment by vanbroup** [comment]
Add this in 4a75188
