### ISSUE TITLE
Associate the 'related-implementation' through datatracker

### ISSUE THREAD

**Issue by ounsworth** [vanbroup/acme-auto-discovery#13]
From Charles Eckel:

> I am catching up on this thread and would like to share a suggestion for your consideration. It seems a great deal of helpful discussion was triggered as a result of the implementation at [https://github.com/as207960/certbot/tree/auto-discovery](https://urldefense.com/v3/__https:/github.com/as207960/certbot/tree/auto-discovery__;!!FJ-Y8qCqXTj2!eY4H58dN5hWOQQ7xZjg2r0R2IahaCWEbFDNt9GmqbKbIx-05kSM741cAzzLVS66-oWM9dTGfOdwWwymahVI$). It might we appropriate to associate this as an Additional Resource using the “related-implementation” tag in the Datatracker. More info on this tag can be found here: [https://www.ietf.org/archive/id/draft-eckel-edm-find-code-03.html#name-datatracker](https://urldefense.com/v3/__https:/www.ietf.org/archive/id/draft-eckel-edm-find-code-03.html*name-datatracker__;Iw!!FJ-Y8qCqXTj2!eY4H58dN5hWOQQ7xZjg2r0R2IahaCWEbFDNt9GmqbKbIx-05kSM741cAzzLVS66-oWM9dTGfOdwWKL7DAyo$).

**Comment by vanbroup** [comment]
A link to the repository and list of related implementations has now been added to the datatracker with a link to the wiki: https://github.com/vanbroup/acme-auto-discovery/wiki/Implementations

![image](https://github.com/vanbroup/acme-auto-discovery/assets/722070/60068a47-6d12-48c0-9faa-50d0e0cdac63)
