### ISSUE TITLE
Security Consideration about effects of DNS poisoning

### ISSUE THREAD

**Issue by ounsworth** [vanbroup/acme-auto-discovery#16]
If the DNS is poisoned, then the ACME client can be forced to get a cert from evil.ca. That could lead to a DoS where the ACME client returns success even though it received a cert from evil.ca.

Within the Public CA usecase, you can fix it my checking that the cert you get back was from one of the CAs in your OS' trust store.

**Comment by vanbroup** [comment]
@ounsworth please review section 9.4: 
https://vanbroup.github.io/acme-auto-discovery/draft-vanbrouwershaven-acme-auto-discovery.html#section-9.4

**Comment by ounsworth** [comment]
Looks good.
