### ISSUE TITLE
Fix contradiction between definition and examples of priority

### ISSUE THREAD

**Issue by aarongable** [vanbroup/acme-auto-discovery#2]
Section 3.1.2:
> the value "1" represents the highest priority, and subsequent values like "2", "3", and so on, indicate progressively lower priorities.

Section 3.2:
> The CAA record with "ca2.example" has a higher priority value of 2, indicating it should be attempted first. The CAA record with "ca1.example" has a lower priority value of 1, indicating it should be attempted second.

This contradicts Section 3.1.2, which says that "2" is a lower priority than "1".

Section 3.2:
> CAA records that do not explicitly specify a priority are automatically assigned the highest priority, which is 0.

This contradicts Section 3.1.2, which says that "1" is the highest priority.

I'd file a PR to fix this, but I'm not sure which direction you'd prefer to fix it in!

**Comment by aarongable** [comment]
Yeah, I think that the combination of:
- lower numbers mean higher priority
- no number at all means the lowest priority

probably leads to the most intuitive behavior

**Comment by vanbroup** [comment]
That works for me!
