### ISSUE TITLE
Add a "Protocol Overview" section

### ISSUE THREAD

**Issue by ounsworth** [vanbroup/acme-auto-discovery#6]
Comment from Richard Barnes:

> A brief "protocol overview" section might be helpful to capture the intended happy-path flow.

https://mailarchive.ietf.org/arch/msg/acme/4p523wENVeqgodyIn7TmwarCIgU/

**Comment by ounsworth** [comment]
Perhaps this is as simple as bringing Section 5: ACME Client Behaviour to the beginning (or duplicating part of it to the beginning).

**Comment by vanbroup** [comment]
A Protocol Overview section has been added on top in commit 61b6b22
