### ISSUE TITLE
Correct IANA registry for CAA attributes

### ISSUE THREAD

**Issue by ounsworth** [vanbroup/acme-auto-discovery#8]
From Fraser Tweedale:

> Regarding registration of CAA attributes (IANA considerations): they
need to be registered in the "Certification Authority Restriction
Properties" registry:
https://www.iana.org/assignments/pkix-parameters/pkix-parameters.xhtml#caa-properties

https://mailarchive.ietf.org/arch/msg/acme/o-P1fOtiIDyQvwkdXJJ93S5jZKI/

**Comment by vanbroup** [comment]
This is a parameter and not a property, I don't think there is a registry for parameters. Parameters can be CA specific.

**Comment by vanbroup** [comment]
Duplicate of #14
